### ISSUE TITLE
error building rtems-tools

### ISSUE THREAD

**Issue by Rashidwi** [grisp/grisp2-rtems-toolchain#56]
Attempting to run `make install` produces the following error:
----------------------------------------------------------------------------------------------------------------
building: rtems-tools-f408c0f8d935d53c232c67bed39e4018fd8d7a2a-1
error: building rtems-tools-f408c0f8d935d53c232c67bed39e4018fd8d7a2a-1
Build FAILED
error: failure to create error report
Build Set: Time 0:11:00.262659
Traceback (most recent call last):
  File "../source-builder/sb/cmd-set-builder.py", line 26, in <module>
    setbuilder.run()
  File "/media/Dev/External/grisp/toolchain/grisp2-rtems-toolchain/external/rtems-source-builder/source-builder/sb/setbuilder.py", line 736, in run
    b.build(deps, mail = mail)
  File "/media/Dev/External/grisp/toolchain/grisp2-rtems-toolchain/external/rtems-source-builder/source-builder/sb/setbuilder.py", line 473, in build
    self.build_package(configs[s], b)
  File "/media/Dev/External/grisp/toolchain/grisp2-rtems-toolchain/external/rtems-source-builder/source-builder/sb/setbuilder.py", line 258, in build_package
    _build.make()
  File "/media/Dev/External/grisp/toolchain/grisp2-rtems-toolchain/external/rtems-source-builder/source-builder/sb/build.py", line 603, in make
    self._generate_report_('Build: %s' % (gerr))
  File "/media/Dev/External/grisp/toolchain/grisp2-rtems-toolchain/external/rtems-source-builder/source-builder/sb/build.py", line 126, in _generate_report_
    self.opts, header, footer)
  File "/media/Dev/External/grisp/toolchain/grisp2-rtems-toolchain/external/rtems-source-builder/source-builder/sb/ereport.py", line 56, in generate
    l.write(os.linesep.join(r))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 69: ordinal not in range(128)
make: *** [Makefile:104: toolchain] Error 1

----------------------------------------------------
`uname -a`: 
Linux gratitude 6.10.8-1-default #1 SMP PREEMPT_DYNAMIC Thu Sep  5 05:47:00 UTC 2024 (db7c2e2) x86
_64 x86_64 x86_64 GNU/Linux

`erl version`:
Erlang/OTP 27 [erts-15.0.1] [source] [64-bit] [smp:24:24] [ds:24:24:10] [async-threads:1] [jit:ns]
 [systemtap]

Eshell V15.0.1 (press Ctrl+G to abort, type help(). for help)

Any other information required to help diagnose this?

**Comment by ziopio** [comment]
Hello, we usually do not reccomend to anyone to build the toolchain. In case you just need to build OTP for GRiSP, with some custom C sources, we recommend to use one of our prebuilt toolchains, you can check the wiki here: https://github.com/grisp/grisp/wiki/Building-the-VM-from-source#pre-built-toolchains 

The only case in which you need to do what you are doing is if you plan to extend the toolchain with more software. For example you might need it in case you want to include a specific C library in you projects. If this is the case, me and my team would be interested to know what you are working on :)

The error is in a python script, so I would check which python version you are running.

**Comment by ziopio** [comment]
Unfortunatly our mix_grisp plugin is very limited, you can only use it to deploy using a prebuilt OTP which is automatically downloaded. That said 99% of the functionality needed to build OTP is implemented in `grisp_tools`. To make it available in Mix is just a matter of getting options from a mix project and feed it to grisp_tools. 

This translates in adding a mix task i.e.: `mix grisp.build` which takes your project grisp config and toolchain location and builds OTP with your C code. Currently we only support this in our `rebar3_grisp` plugin for `rebar3` with the command `rebar3 grisp build`

In case you or anyone would like to contribute on the https://github.com/grisp/mix_grisp plugin we are happy to give support and guidance. PRs are always welcome :)
